# Generated by Django 4.0.4 on 2022-04-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='cat',
            field=models.CharField(default='General', max_length=255, verbose_name='Category'),
        ),
    ]
